repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
# hook installation required for the following hook to work: pre-commit install --hook-type commit-msg
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.2.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []